// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  claimKey: __t.string().primaryKey().name("claim_key"),
  accountId: __t.string().name("account_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  dayIndex: __t.u8().name("day_index"),
  pointsGranted: __t.u32().name("points_granted"),
  claimedAt: __t.timestamp().name("claimed_at"),
});
