// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  accountId: __t.string().name("account_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  avatarKey: __t.string().name("avatar_key"),
  pricePaid: __t.u32().name("price_paid"),
  unlockedAt: __t.timestamp().name("unlocked_at"),
});
