// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  accountId: __t.string().name("account_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  delta: __t.i64(),
  balanceAfter: __t.i64().name("balance_after"),
  reason: __t.string(),
  detail: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
