// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  email: __t.string().primaryKey(),
  accountId: __t.string().name("account_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  displayName: __t.string().name("display_name"),
  gender: __t.string(),
  birthDate: __t.option(__t.timestamp()).name("birth_date"),
  profileNote: __t.string().name("profile_note"),
});
