// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  avatarKey: __t.string(),
  seriesKey: __t.string(),
  basePath: __t.string(),
  fileName: __t.string(),
  pricePoints: __t.u32(),
  isPublished: __t.bool(),
  sortOrder: __t.u32(),
};
