// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sanctionId: __t.string().name("sanction_id"),
  appellantIdentity: __t.identity().name("appellant_identity"),
  detailText: __t.string().name("detail_text"),
  status: __t.string(),
  adminNote: __t.string().name("admin_note"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
});
