// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  avatarKey: __t.string().primaryKey().name("avatar_key"),
  seriesKey: __t.string().name("series_key"),
  basePath: __t.string().name("base_path"),
  fileName: __t.string().name("file_name"),
  pricePoints: __t.u32().name("price_points"),
  isPublished: __t.bool().name("is_published"),
  sortOrder: __t.u32().name("sort_order"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  seriesDisplayName: __t.string().name("series_display_name"),
});
