// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  capsuleId: __t.string().name("capsule_id"),
  collectorIdentity: __t.identity().name("collector_identity"),
  snapshotContent: __t.string().name("snapshot_content"),
  snapshotAuthorEmail: __t.string().name("snapshot_author_email"),
  snapshotScheduledAt: __t.timestamp().name("snapshot_scheduled_at"),
  snapshotCapsuleType: __t.u8().name("snapshot_capsule_type"),
  snapshotPublisherGender: __t.string().name("snapshot_publisher_gender"),
  snapshotPublisherBirthDate: __t.option(__t.timestamp()).name("snapshot_publisher_birth_date"),
  snapshotPublisherAccountId: __t.string().name("snapshot_publisher_account_id"),
  createdAt: __t.timestamp().name("created_at"),
});
