// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  authorIdentity: __t.identity().name("author_identity"),
  authorEmail: __t.string().name("author_email"),
  authorAccountId: __t.string().name("author_account_id"),
  authorDisplayName: __t.string().name("author_display_name"),
  authorGender: __t.string().name("author_gender"),
  authorBirthDate: __t.option(__t.timestamp()).name("author_birth_date"),
  content: __t.string(),
  scheduledAt: __t.timestamp().name("scheduled_at"),
  isWaitListVisible: __t.bool().name("is_wait_list_visible"),
  exchangeLog: __t.string().name("exchange_log"),
  createdAt: __t.timestamp().name("created_at"),
  capsuleType: __t.u8().name("capsule_type"),
});
