// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  sourceMessageId: __t.string().name("source_message_id"),
  threadGuestIdentity: __t.identity().name("thread_guest_identity"),
  threadGuestAccountId: __t.string().name("thread_guest_account_id"),
  authorIdentity: __t.identity().name("author_identity"),
  authorAccountId: __t.string().name("author_account_id"),
  body: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
