// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  capsuleId: __t.string().primaryKey().name("capsule_id"),
  authorIdentity: __t.identity().name("author_identity"),
  isProfilePublic: __t.bool().name("is_profile_public"),
  isDeleted: __t.bool().name("is_deleted"),
});
