// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddCapsulePrivateMessageReducer from "./add_capsule_private_message_reducer";
import AddSquareCommentReducer from "./add_square_comment_reducer";
import AdminApplyUserSanctionReducer from "./admin_apply_user_sanction_reducer";
import AdminDeleteCapsuleReducer from "./admin_delete_capsule_reducer";
import AdminDeleteRoleRecordReducer from "./admin_delete_role_record_reducer";
import AdminDeleteSquarePostReducer from "./admin_delete_square_post_reducer";
import AdminPurgeAllRolesReducer from "./admin_purge_all_roles_reducer";
import AdminResetPasswordByEmailReducer from "./admin_reset_password_by_email_reducer";
import AdminSetUserSanctionStatusReducer from "./admin_set_user_sanction_status_reducer";
import AdminUpdateAppealTicketReducer from "./admin_update_appeal_ticket_reducer";
import AdminUpdateReportTicketReducer from "./admin_update_report_ticket_reducer";
import AppendLetterExchangeReducer from "./append_letter_exchange_reducer";
import ChangePasswordReducer from "./change_password_reducer";
import ClaimOrphanSuperAdminReducer from "./claim_orphan_super_admin_reducer";
import CreateAppealTicketReducer from "./create_appeal_ticket_reducer";
import CreateReportTicketReducer from "./create_report_ticket_reducer";
import DeleteCapsuleMessageReducer from "./delete_capsule_message_reducer";
import DeleteScheduledMessageReducer from "./delete_scheduled_message_reducer";
import DevCleanupSeedCapsuleSquarePostsReducer from "./dev_cleanup_seed_capsule_square_posts_reducer";
import DevSeedDemoUsersReducer from "./dev_seed_demo_users_reducer";
import DevSeedSecretCapsulePostsReducer from "./dev_seed_secret_capsule_posts_reducer";
import FavoriteCapsuleReducer from "./favorite_capsule_reducer";
import FavoriteSquarePostReducer from "./favorite_square_post_reducer";
import LoginAccountReducer from "./login_account_reducer";
import PublishToSquareReducer from "./publish_to_square_reducer";
import RegisterAccountReducer from "./register_account_reducer";
import RestoreCapsuleMessageReducer from "./restore_capsule_message_reducer";
import SendCapsuleMessageReducer from "./send_capsule_message_reducer";
import SendDirectMessageReducer from "./send_direct_message_reducer";
import SendScheduledMessageReducer from "./send_scheduled_message_reducer";
import SetAdminRoleReducer from "./set_admin_role_reducer";
import SetAgeYearsReducer from "./set_age_years_reducer";
import SetSquareReactionReducer from "./set_square_reaction_reducer";
import UnfavoriteCapsuleReducer from "./unfavorite_capsule_reducer";
import UnfavoriteSquarePostReducer from "./unfavorite_square_post_reducer";
import UnpublishFromSquareReducer from "./unpublish_from_square_reducer";
import UpdateAccountProfileReducer from "./update_account_profile_reducer";
import UpdateScheduledMessageReducer from "./update_scheduled_message_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountProfileRow from "./account_profile_table";
import AdminAuditLogRow from "./admin_audit_log_table";
import AdminRoleRow from "./admin_role_table";
import AppealTicketRow from "./appeal_ticket_table";
import CapsuleFavoriteRow from "./capsule_favorite_table";
import CapsuleMessageRow from "./capsule_message_table";
import CapsuleMessageSpaceStateRow from "./capsule_message_space_state_table";
import CapsulePrivateForMeRow from "./capsule_private_for_me_table";
import ModerationActionLogRow from "./moderation_action_log_table";
import ModerationQueueRow from "./moderation_queue_table";
import RecentSquarePostsRow from "./recent_square_posts_table";
import ReportTargetSnapshotRow from "./report_target_snapshot_table";
import ReportTicketRow from "./report_ticket_table";
import ScheduledMessageRow from "./scheduled_message_table";
import SquareCommentRow from "./square_comment_table";
import SquareFavoriteRow from "./square_favorite_table";
import SquarePostRow from "./square_post_table";
import SquareReactionRow from "./square_reaction_table";
import UserSanctionRow from "./user_sanction_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accountProfile: __table({
    name: 'account_profile',
    indexes: [
      { accessor: 'accountId', name: 'account_profile_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'email', name: 'account_profile_email_idx_btree', algorithm: 'btree', columns: [
        'email',
      ] },
      { accessor: 'ownerIdentity', name: 'account_profile_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'account_profile_account_id_key', constraint: 'unique', columns: ['accountId'] },
      { name: 'account_profile_email_key', constraint: 'unique', columns: ['email'] },
      { name: 'account_profile_owner_identity_key', constraint: 'unique', columns: ['ownerIdentity'] },
    ],
  }, AccountProfileRow),
  adminAuditLog: __table({
    name: 'admin_audit_log',
    indexes: [
      { accessor: 'id', name: 'admin_audit_log_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'admin_audit_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AdminAuditLogRow),
  adminRole: __table({
    name: 'admin_role',
    indexes: [
      { accessor: 'accountId', name: 'admin_role_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'adminIdentity', name: 'admin_role_admin_identity_idx_btree', algorithm: 'btree', columns: [
        'adminIdentity',
      ] },
    ],
    constraints: [
      { name: 'admin_role_account_id_key', constraint: 'unique', columns: ['accountId'] },
      { name: 'admin_role_admin_identity_key', constraint: 'unique', columns: ['adminIdentity'] },
    ],
  }, AdminRoleRow),
  appealTicket: __table({
    name: 'appeal_ticket',
    indexes: [
      { accessor: 'appellantIdentity', name: 'appeal_ticket_appellant_identity_idx_btree', algorithm: 'btree', columns: [
        'appellantIdentity',
      ] },
      { accessor: 'id', name: 'appeal_ticket_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sanctionId', name: 'appeal_ticket_sanction_id_idx_btree', algorithm: 'btree', columns: [
        'sanctionId',
      ] },
    ],
    constraints: [
      { name: 'appeal_ticket_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AppealTicketRow),
  capsuleFavorite: __table({
    name: 'capsule_favorite',
    indexes: [
      { accessor: 'capsuleId', name: 'capsule_favorite_capsule_id_idx_btree', algorithm: 'btree', columns: [
        'capsuleId',
      ] },
      { accessor: 'collectorIdentity', name: 'capsule_favorite_collector_identity_idx_btree', algorithm: 'btree', columns: [
        'collectorIdentity',
      ] },
      { accessor: 'id', name: 'capsule_favorite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'capsule_favorite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CapsuleFavoriteRow),
  capsuleMessage: __table({
    name: 'capsule_message',
    indexes: [
      { accessor: 'authorAccountId', name: 'capsule_message_author_account_id_idx_btree', algorithm: 'btree', columns: [
        'authorAccountId',
      ] },
      { accessor: 'authorIdentity', name: 'capsule_message_author_identity_idx_btree', algorithm: 'btree', columns: [
        'authorIdentity',
      ] },
      { accessor: 'id', name: 'capsule_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'capsule_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CapsuleMessageRow),
  capsuleMessageSpaceState: __table({
    name: 'capsule_message_space_state',
    indexes: [
      { accessor: 'authorIdentity', name: 'capsule_message_space_state_author_identity_idx_btree', algorithm: 'btree', columns: [
        'authorIdentity',
      ] },
      { accessor: 'capsuleId', name: 'capsule_message_space_state_capsule_id_idx_btree', algorithm: 'btree', columns: [
        'capsuleId',
      ] },
    ],
    constraints: [
      { name: 'capsule_message_space_state_capsule_id_key', constraint: 'unique', columns: ['capsuleId'] },
    ],
  }, CapsuleMessageSpaceStateRow),
  moderationActionLog: __table({
    name: 'moderation_action_log',
    indexes: [
      { accessor: 'id', name: 'moderation_action_log_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'moderation_action_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModerationActionLogRow),
  moderationQueue: __table({
    name: 'moderation_queue',
    indexes: [
      { accessor: 'reportId', name: 'moderation_queue_report_id_idx_btree', algorithm: 'btree', columns: [
        'reportId',
      ] },
    ],
    constraints: [
      { name: 'moderation_queue_report_id_key', constraint: 'unique', columns: ['reportId'] },
    ],
  }, ModerationQueueRow),
  reportTargetSnapshot: __table({
    name: 'report_target_snapshot',
    indexes: [
      { accessor: 'id', name: 'report_target_snapshot_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'reportId', name: 'report_target_snapshot_report_id_idx_btree', algorithm: 'btree', columns: [
        'reportId',
      ] },
    ],
    constraints: [
      { name: 'report_target_snapshot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReportTargetSnapshotRow),
  reportTicket: __table({
    name: 'report_ticket',
    indexes: [
      { accessor: 'id', name: 'report_ticket_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'reporterIdentity', name: 'report_ticket_reporter_identity_idx_btree', algorithm: 'btree', columns: [
        'reporterIdentity',
      ] },
      { accessor: 'targetId', name: 'report_ticket_target_id_idx_btree', algorithm: 'btree', columns: [
        'targetId',
      ] },
    ],
    constraints: [
      { name: 'report_ticket_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReportTicketRow),
  scheduledMessage: __table({
    name: 'scheduled_message',
    indexes: [
      { accessor: 'id', name: 'scheduled_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'recipientEmail', name: 'scheduled_message_recipient_email_idx_btree', algorithm: 'btree', columns: [
        'recipientEmail',
      ] },
      { accessor: 'senderEmail', name: 'scheduled_message_sender_email_idx_btree', algorithm: 'btree', columns: [
        'senderEmail',
      ] },
      { accessor: 'senderIdentity', name: 'scheduled_message_sender_identity_idx_btree', algorithm: 'btree', columns: [
        'senderIdentity',
      ] },
    ],
    constraints: [
      { name: 'scheduled_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ScheduledMessageRow),
  squareComment: __table({
    name: 'square_comment',
    indexes: [
      { accessor: 'authorIdentity', name: 'square_comment_author_identity_idx_btree', algorithm: 'btree', columns: [
        'authorIdentity',
      ] },
      { accessor: 'id', name: 'square_comment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'postSourceMessageId', name: 'square_comment_post_source_message_id_idx_btree', algorithm: 'btree', columns: [
        'postSourceMessageId',
      ] },
    ],
    constraints: [
      { name: 'square_comment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SquareCommentRow),
  squareFavorite: __table({
    name: 'square_favorite',
    indexes: [
      { accessor: 'collectorIdentity', name: 'square_favorite_collector_identity_idx_btree', algorithm: 'btree', columns: [
        'collectorIdentity',
      ] },
      { accessor: 'id', name: 'square_favorite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'postSourceMessageId', name: 'square_favorite_post_source_message_id_idx_btree', algorithm: 'btree', columns: [
        'postSourceMessageId',
      ] },
    ],
    constraints: [
      { name: 'square_favorite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SquareFavoriteRow),
  squarePost: __table({
    name: 'square_post',
    indexes: [
      { accessor: 'createdAt', name: 'square_post_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'publisherIdentity', name: 'square_post_publisher_identity_idx_btree', algorithm: 'btree', columns: [
        'publisherIdentity',
      ] },
      { accessor: 'sourceMessageId', name: 'square_post_source_message_id_idx_btree', algorithm: 'btree', columns: [
        'sourceMessageId',
      ] },
    ],
    constraints: [
      { name: 'square_post_source_message_id_key', constraint: 'unique', columns: ['sourceMessageId'] },
    ],
  }, SquarePostRow),
  squareReaction: __table({
    name: 'square_reaction',
    indexes: [
      { accessor: 'id', name: 'square_reaction_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'postSourceMessageId', name: 'square_reaction_post_source_message_id_idx_btree', algorithm: 'btree', columns: [
        'postSourceMessageId',
      ] },
      { accessor: 'reactorIdentity', name: 'square_reaction_reactor_identity_idx_btree', algorithm: 'btree', columns: [
        'reactorIdentity',
      ] },
    ],
    constraints: [
      { name: 'square_reaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SquareReactionRow),
  userSanction: __table({
    name: 'user_sanction',
    indexes: [
      { accessor: 'id', name: 'user_sanction_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'targetIdentity', name: 'user_sanction_target_identity_idx_btree', algorithm: 'btree', columns: [
        'targetIdentity',
      ] },
    ],
    constraints: [
      { name: 'user_sanction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserSanctionRow),
  capsule_private_for_me: __table({
    name: 'capsule_private_for_me',
    indexes: [
    ],
    constraints: [
    ],
  }, CapsulePrivateForMeRow),
  recent_square_posts: __table({
    name: 'recent_square_posts',
    indexes: [
    ],
    constraints: [
    ],
  }, RecentSquarePostsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_capsule_private_message", AddCapsulePrivateMessageReducer),
  __reducerSchema("add_square_comment", AddSquareCommentReducer),
  __reducerSchema("admin_apply_user_sanction", AdminApplyUserSanctionReducer),
  __reducerSchema("admin_delete_capsule", AdminDeleteCapsuleReducer),
  __reducerSchema("admin_delete_role_record", AdminDeleteRoleRecordReducer),
  __reducerSchema("admin_delete_square_post", AdminDeleteSquarePostReducer),
  __reducerSchema("admin_purge_all_roles", AdminPurgeAllRolesReducer),
  __reducerSchema("admin_reset_password_by_email", AdminResetPasswordByEmailReducer),
  __reducerSchema("admin_set_user_sanction_status", AdminSetUserSanctionStatusReducer),
  __reducerSchema("admin_update_appeal_ticket", AdminUpdateAppealTicketReducer),
  __reducerSchema("admin_update_report_ticket", AdminUpdateReportTicketReducer),
  __reducerSchema("append_letter_exchange", AppendLetterExchangeReducer),
  __reducerSchema("change_password", ChangePasswordReducer),
  __reducerSchema("claim_orphan_super_admin", ClaimOrphanSuperAdminReducer),
  __reducerSchema("create_appeal_ticket", CreateAppealTicketReducer),
  __reducerSchema("create_report_ticket", CreateReportTicketReducer),
  __reducerSchema("delete_capsule_message", DeleteCapsuleMessageReducer),
  __reducerSchema("delete_scheduled_message", DeleteScheduledMessageReducer),
  __reducerSchema("dev_cleanup_seed_capsule_square_posts", DevCleanupSeedCapsuleSquarePostsReducer),
  __reducerSchema("dev_seed_demo_users", DevSeedDemoUsersReducer),
  __reducerSchema("dev_seed_secret_capsule_posts", DevSeedSecretCapsulePostsReducer),
  __reducerSchema("favorite_capsule", FavoriteCapsuleReducer),
  __reducerSchema("favorite_square_post", FavoriteSquarePostReducer),
  __reducerSchema("login_account", LoginAccountReducer),
  __reducerSchema("publish_to_square", PublishToSquareReducer),
  __reducerSchema("register_account", RegisterAccountReducer),
  __reducerSchema("restore_capsule_message", RestoreCapsuleMessageReducer),
  __reducerSchema("send_capsule_message", SendCapsuleMessageReducer),
  __reducerSchema("send_direct_message", SendDirectMessageReducer),
  __reducerSchema("send_scheduled_message", SendScheduledMessageReducer),
  __reducerSchema("set_admin_role", SetAdminRoleReducer),
  __reducerSchema("set_age_years", SetAgeYearsReducer),
  __reducerSchema("set_square_reaction", SetSquareReactionReducer),
  __reducerSchema("unfavorite_capsule", UnfavoriteCapsuleReducer),
  __reducerSchema("unfavorite_square_post", UnfavoriteSquarePostReducer),
  __reducerSchema("unpublish_from_square", UnpublishFromSquareReducer),
  __reducerSchema("update_account_profile", UpdateAccountProfileReducer),
  __reducerSchema("update_scheduled_message", UpdateScheduledMessageReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

