// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  reporterIdentity: __t.identity().name("reporter_identity"),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  reasonCode: __t.string().name("reason_code"),
  detailText: __t.string().name("detail_text"),
  evidenceJson: __t.string().name("evidence_json"),
  status: __t.string(),
  priority: __t.u8(),
  assignedAdminIdentity: __t.option(__t.identity()).name("assigned_admin_identity"),
  resolutionNote: __t.string().name("resolution_note"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
});
