// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  senderIdentity: __t.identity().name("sender_identity"),
  senderEmail: __t.string().name("sender_email"),
  recipientEmail: __t.string().name("recipient_email"),
  content: __t.string(),
  scheduledAt: __t.timestamp().name("scheduled_at"),
  isWaitListVisible: __t.bool().name("is_wait_list_visible"),
  exchangeLog: __t.string().name("exchange_log"),
  createdAt: __t.timestamp().name("created_at"),
});
