// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  content: __t.string(),
  capsuleType: __t.u8(),
  scheduledAt: __t.option(__t.timestamp()),
  isWaitListVisible: __t.bool(),
  isProfilePublic: __t.bool(),
  publishToSquare: __t.bool(),
  squareRepliesPublic: __t.bool(),
  squareIncludeThread: __t.bool(),
  squareIncludeCapsulePrivate: __t.bool(),
  squareShowSender: __t.bool(),
  squareShowRecipient: __t.bool(),
};
