// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sourceMessageId: __t.string().primaryKey().name("source_message_id"),
  publisherIdentity: __t.identity().name("publisher_identity"),
  publisherAccountId: __t.string().name("publisher_account_id"),
  snapshotPublisherName: __t.string().name("snapshot_publisher_name"),
  snapshotPublisherGender: __t.string().name("snapshot_publisher_gender"),
  snapshotPublisherBirthDate: __t.option(__t.timestamp()).name("snapshot_publisher_birth_date"),
  repliesPublic: __t.bool().name("replies_public"),
  includeThreadInSnapshot: __t.bool().name("include_thread_in_snapshot"),
  snapshotContent: __t.string().name("snapshot_content"),
  snapshotSenderEmail: __t.string().name("snapshot_sender_email"),
  snapshotRecipientEmail: __t.string().name("snapshot_recipient_email"),
  snapshotScheduledAt: __t.timestamp().name("snapshot_scheduled_at"),
  showSenderOnSquare: __t.bool().name("show_sender_on_square"),
  showRecipientOnSquare: __t.bool().name("show_recipient_on_square"),
  createdAt: __t.timestamp().name("created_at"),
  includeCapsulePrivateInSnapshot: __t.bool().name("include_capsule_private_in_snapshot"),
  sourceKind: __t.string().name("source_kind"),
  sourceId: __t.string().name("source_id"),
});
