// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  postSourceMessageId: __t.string().name("post_source_message_id"),
  authorIdentity: __t.identity().name("author_identity"),
  body: __t.string(),
  parentCommentId: __t.string().name("parent_comment_id"),
  createdAt: __t.timestamp().name("created_at"),
});
