// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountAvatarUnlock = __t.object("AccountAvatarUnlock", {
  id: __t.string(),
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  avatarKey: __t.string(),
  pricePaid: __t.u32(),
  unlockedAt: __t.timestamp(),
});
export type AccountAvatarUnlock = __Infer<typeof AccountAvatarUnlock>;

export const AccountDailyRewardClaim = __t.object("AccountDailyRewardClaim", {
  claimKey: __t.string(),
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  dayIndex: __t.u8(),
  pointsGranted: __t.u32(),
  claimedAt: __t.timestamp(),
});
export type AccountDailyRewardClaim = __Infer<typeof AccountDailyRewardClaim>;

export const AccountEngagementSettlement = __t.object("AccountEngagementSettlement", {
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  lastSettledOrdinal: __t.i64(),
  lastActiveCount: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type AccountEngagementSettlement = __Infer<typeof AccountEngagementSettlement>;

export const AccountPasswordResetRequired = __t.object("AccountPasswordResetRequired", {
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  required: __t.bool(),
  issuedAt: __t.timestamp(),
});
export type AccountPasswordResetRequired = __Infer<typeof AccountPasswordResetRequired>;

export const AccountPointsLedger = __t.object("AccountPointsLedger", {
  id: __t.string(),
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  delta: __t.i64(),
  balanceAfter: __t.i64(),
  reason: __t.string(),
  detail: __t.string(),
  createdAt: __t.timestamp(),
});
export type AccountPointsLedger = __Infer<typeof AccountPointsLedger>;

export const AccountPointsWallet = __t.object("AccountPointsWallet", {
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  balance: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AccountPointsWallet = __Infer<typeof AccountPointsWallet>;

export const AccountProfile = __t.object("AccountProfile", {
  email: __t.string(),
  accountId: __t.string(),
  ownerIdentity: __t.identity(),
  displayName: __t.string(),
  gender: __t.string(),
  birthDate: __t.option(__t.timestamp()),
  profileNote: __t.string(),
  avatarKey: __t.string(),
});
export type AccountProfile = __Infer<typeof AccountProfile>;

export const AccountProfileCreatedAt = __t.object("AccountProfileCreatedAt", {
  email: __t.string(),
  accountId: __t.string(),
  createdAt: __t.timestamp(),
});
export type AccountProfileCreatedAt = __Infer<typeof AccountProfileCreatedAt>;

export const AccountSecret = __t.object("AccountSecret", {
  email: __t.string(),
  passwordHash: __t.string(),
});
export type AccountSecret = __Infer<typeof AccountSecret>;

export const AdminAuditLog = __t.object("AdminAuditLog", {
  id: __t.string(),
  adminIdentity: __t.identity(),
  adminAccountId: __t.string(),
  actionType: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  detail: __t.string(),
  createdAt: __t.timestamp(),
});
export type AdminAuditLog = __Infer<typeof AdminAuditLog>;

export const AdminRole = __t.object("AdminRole", {
  adminIdentity: __t.identity(),
  accountId: __t.string(),
  role: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AdminRole = __Infer<typeof AdminRole>;

export const AppealTicket = __t.object("AppealTicket", {
  id: __t.string(),
  sanctionId: __t.string(),
  appellantIdentity: __t.identity(),
  detailText: __t.string(),
  status: __t.string(),
  adminNote: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type AppealTicket = __Infer<typeof AppealTicket>;

export const AvatarCatalogItem = __t.object("AvatarCatalogItem", {
  avatarKey: __t.string(),
  seriesKey: __t.string(),
  basePath: __t.string(),
  fileName: __t.string(),
  pricePoints: __t.u32(),
  isPublished: __t.bool(),
  sortOrder: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  seriesDisplayName: __t.string(),
});
export type AvatarCatalogItem = __Infer<typeof AvatarCatalogItem>;

export const AvatarSeriesOrder = __t.object("AvatarSeriesOrder", {
  seriesKey: __t.string(),
  sortOrder: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type AvatarSeriesOrder = __Infer<typeof AvatarSeriesOrder>;

export const CapsuleFavorite = __t.object("CapsuleFavorite", {
  id: __t.string(),
  capsuleId: __t.string(),
  collectorIdentity: __t.identity(),
  snapshotContent: __t.string(),
  snapshotAuthorEmail: __t.string(),
  snapshotScheduledAt: __t.timestamp(),
  snapshotCapsuleType: __t.u8(),
  snapshotPublisherGender: __t.string(),
  snapshotPublisherBirthDate: __t.option(__t.timestamp()),
  snapshotPublisherAccountId: __t.string(),
  createdAt: __t.timestamp(),
});
export type CapsuleFavorite = __Infer<typeof CapsuleFavorite>;

export const CapsuleMessage = __t.object("CapsuleMessage", {
  id: __t.string(),
  authorIdentity: __t.identity(),
  authorEmail: __t.string(),
  authorAccountId: __t.string(),
  authorDisplayName: __t.string(),
  authorGender: __t.string(),
  authorBirthDate: __t.option(__t.timestamp()),
  content: __t.string(),
  scheduledAt: __t.timestamp(),
  isWaitListVisible: __t.bool(),
  exchangeLog: __t.string(),
  createdAt: __t.timestamp(),
  capsuleType: __t.u8(),
});
export type CapsuleMessage = __Infer<typeof CapsuleMessage>;

export const CapsuleMessageSpaceState = __t.object("CapsuleMessageSpaceState", {
  capsuleId: __t.string(),
  authorIdentity: __t.identity(),
  isProfilePublic: __t.bool(),
  isDeleted: __t.bool(),
});
export type CapsuleMessageSpaceState = __Infer<typeof CapsuleMessageSpaceState>;

export const CapsulePrivateForMe = __t.object("CapsulePrivateForMe", {});
export type CapsulePrivateForMe = __Infer<typeof CapsulePrivateForMe>;

export const CapsulePrivateMessage = __t.object("CapsulePrivateMessage", {
  id: __t.string(),
  sourceMessageId: __t.string(),
  threadGuestIdentity: __t.identity(),
  threadGuestAccountId: __t.string(),
  authorIdentity: __t.identity(),
  authorAccountId: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type CapsulePrivateMessage = __Infer<typeof CapsulePrivateMessage>;

export const EmailOtpAuditLog = __t.object("EmailOtpAuditLog", {
  id: __t.string(),
  challengeKey: __t.string(),
  purpose: __t.string(),
  email: __t.string(),
  action: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  operatorIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type EmailOtpAuditLog = __Infer<typeof EmailOtpAuditLog>;

export const EmailOtpChallenge = __t.object("EmailOtpChallenge", {
  challengeKey: __t.string(),
  purpose: __t.string(),
  email: __t.string(),
  otpSalt: __t.string(),
  otpHash: __t.string(),
  attemptCount: __t.u16(),
  sendCount: __t.u16(),
  expiresAt: __t.timestamp(),
  resendAfter: __t.timestamp(),
  lockedUntil: __t.option(__t.timestamp()),
  lastRequestedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type EmailOtpChallenge = __Infer<typeof EmailOtpChallenge>;

export const EmailOtpSession = __t.object("EmailOtpSession", {
  sessionKey: __t.string(),
  purpose: __t.string(),
  email: __t.string(),
  ownerIdentity: __t.identity(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type EmailOtpSession = __Infer<typeof EmailOtpSession>;

export const ModerationActionLog = __t.object("ModerationActionLog", {
  id: __t.string(),
  actionType: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  operatorIdentity: __t.identity(),
  note: __t.string(),
  createdAt: __t.timestamp(),
});
export type ModerationActionLog = __Infer<typeof ModerationActionLog>;

export const ModerationQueue = __t.object("ModerationQueue", {
  reportId: __t.string(),
  status: __t.string(),
  priority: __t.u8(),
  assignedAdminIdentity: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ModerationQueue = __Infer<typeof ModerationQueue>;

export const ModuleMigrationDone = __t.object("ModuleMigrationDone", {
  migrationId: __t.string(),
  appliedAt: __t.timestamp(),
});
export type ModuleMigrationDone = __Infer<typeof ModuleMigrationDone>;

export const RecentSquarePosts = __t.object("RecentSquarePosts", {});
export type RecentSquarePosts = __Infer<typeof RecentSquarePosts>;

export const ReportTargetSnapshot = __t.object("ReportTargetSnapshot", {
  id: __t.string(),
  reportId: __t.string(),
  snapshotText: __t.string(),
  snapshotJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReportTargetSnapshot = __Infer<typeof ReportTargetSnapshot>;

export const ReportTicket = __t.object("ReportTicket", {
  id: __t.string(),
  reporterIdentity: __t.identity(),
  targetType: __t.string(),
  targetId: __t.string(),
  reasonCode: __t.string(),
  detailText: __t.string(),
  evidenceJson: __t.string(),
  status: __t.string(),
  priority: __t.u8(),
  assignedAdminIdentity: __t.option(__t.identity()),
  resolutionNote: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  reporterAccountId: __t.string(),
  reporterEmail: __t.string(),
});
export type ReportTicket = __Infer<typeof ReportTicket>;

export const ScheduledMessage = __t.object("ScheduledMessage", {
  id: __t.string(),
  senderIdentity: __t.identity(),
  senderEmail: __t.string(),
  recipientEmail: __t.string(),
  content: __t.string(),
  scheduledAt: __t.timestamp(),
  isWaitListVisible: __t.bool(),
  exchangeLog: __t.string(),
  createdAt: __t.timestamp(),
});
export type ScheduledMessage = __Infer<typeof ScheduledMessage>;

export const SquareComment = __t.object("SquareComment", {
  id: __t.string(),
  postSourceMessageId: __t.string(),
  authorIdentity: __t.identity(),
  body: __t.string(),
  parentCommentId: __t.string(),
  createdAt: __t.timestamp(),
});
export type SquareComment = __Infer<typeof SquareComment>;

export const SquareFavorite = __t.object("SquareFavorite", {
  id: __t.string(),
  postSourceMessageId: __t.string(),
  collectorIdentity: __t.identity(),
  snapshotContent: __t.string(),
  snapshotSenderEmail: __t.string(),
  snapshotRecipientEmail: __t.string(),
  snapshotScheduledAt: __t.timestamp(),
  snapshotShowSender: __t.bool(),
  snapshotShowRecipient: __t.bool(),
  snapshotPublisherGender: __t.string(),
  snapshotPublisherBirthDate: __t.option(__t.timestamp()),
  snapshotPublisherAccountId: __t.string(),
  createdAt: __t.timestamp(),
});
export type SquareFavorite = __Infer<typeof SquareFavorite>;

export const SquarePost = __t.object("SquarePost", {
  sourceMessageId: __t.string(),
  publisherIdentity: __t.identity(),
  publisherAccountId: __t.string(),
  snapshotPublisherName: __t.string(),
  snapshotPublisherGender: __t.string(),
  snapshotPublisherBirthDate: __t.option(__t.timestamp()),
  repliesPublic: __t.bool(),
  includeThreadInSnapshot: __t.bool(),
  snapshotContent: __t.string(),
  snapshotSenderEmail: __t.string(),
  snapshotRecipientEmail: __t.string(),
  snapshotScheduledAt: __t.timestamp(),
  showSenderOnSquare: __t.bool(),
  showRecipientOnSquare: __t.bool(),
  createdAt: __t.timestamp(),
  includeCapsulePrivateInSnapshot: __t.bool(),
  sourceKind: __t.string(),
  sourceId: __t.string(),
  description: __t.string(),
});
export type SquarePost = __Infer<typeof SquarePost>;

export const SquareReaction = __t.object("SquareReaction", {
  id: __t.string(),
  postSourceMessageId: __t.string(),
  reactorIdentity: __t.identity(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
});
export type SquareReaction = __Infer<typeof SquareReaction>;

export const UserSanction = __t.object("UserSanction", {
  id: __t.string(),
  targetIdentity: __t.identity(),
  targetAccountId: __t.string(),
  sanctionType: __t.string(),
  reasonCode: __t.string(),
  detailText: __t.string(),
  status: __t.string(),
  startAt: __t.timestamp(),
  endAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  operatorIdentity: __t.identity(),
});
export type UserSanction = __Infer<typeof UserSanction>;

