// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  targetIdentity: __t.identity().name("target_identity"),
  targetAccountId: __t.string().name("target_account_id"),
  sanctionType: __t.string().name("sanction_type"),
  reasonCode: __t.string().name("reason_code"),
  detailText: __t.string().name("detail_text"),
  status: __t.string(),
  startAt: __t.timestamp().name("start_at"),
  endAt: __t.option(__t.timestamp()).name("end_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  operatorIdentity: __t.identity().name("operator_identity"),
});
